### ISSUE TITLE
DEPRECATED: Directly setting drivers/servers is deprecated, please use Capybara.register_driver/register_server instead

### ISSUE THREAD

**Issue by madleech** [socketry/falcon-capybara#2]
Seems that in Capybara 3.33.0 a change was made to deprecate direct access to `Capybara.servers`.

So the following in [servers.rb](https://github.com/socketry/falcon-capybara/blob/c6cd19285ac0aad85836119d3492d528f94478dc/lib/falcon/capybara/servers.rb#L23) now causes a warning:
```ruby
Capybara.servers[:falcon] = Falcon::Capybara::Wrapper.new
```

I tried setting it to:
```ruby
Capybara.register_server(:falcon) do
	Falcon::Capybara::Wrapper.new
end
```
... but that just fails with the error "Rack application timed out during boot".

Looking at the docs [register_server](https://www.rubydoc.info/github/jnicklas/capybara/Capybara.register_server) expects a block that it can [`.call`](https://github.com/teamcapybara/capybara/blob/476c8508a34cb072489c03d44fe251427605fa40/lib/capybara/server.rb#L77) when it is time to boot. Any ideas?

**Comment by madleech** [comment]
This _sort of_ works:
```ruby
Capybara.register_server(:falcon) do |app, port, host|
	@instance ||= Falcon::Capybara::Wrapper.new
	@instance.call(app, port, host)
end
```

But fails any calls to `Capybara.server.remote`.

**Comment by ioquatix** [comment]
Capybara was firm on their decision to disallow this usage, so we should implement #3.
